/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'velmuruganv' at '10/2/15 8:35 AM' with Gradle 2.6
 *
 * @author velmuruganv, @date 10/2/15 8:35 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
